### ISSUE TITLE
[Sugggestion] Mabye use custom font for time?

### ISSUE THREAD

**Issue by alni** [alni/AlniLargeTimeWatchFace#1]
To give the watch face a more custom-made look, mabye test how a custom font would look like?

### Requirements: ###

* Sans-Serif
* The numbers should have same upper and lower body style (e.x. the _circles_ of the number **"8"** should be the same size)
* The characters should be easily readable at a glanse (even with somewhat poor eye-sight)
    * The tickness should not be _too_ thin, neither too _thick_
    * The width should not be _too_ small or too _large_
    * **No** cursive/big slant; the characters should be aligned with x/y axis (no _sway_ to either sides)
* The fonts should be licensed under an open/permissive license _and_ be free of charge that allows using with a open-source project

Here is a filtered list from Google Web Fonts that _may_ meet these requirements

* <https://fonts.google.com/?category=Sans+Serif&slant=1&thickness=6&width=6>

#### Fonts that _does_ meet the requirements: ####

* **Roboto Condensed** - acceptable thickness, good width even as _condensed_
* **Oswald** - good thickness variations, acceptable width
* **Titillium Web** - many good thickness variations, acceptable width

#### Fonts that does _not_ meet the requirements: ####

* **Josefin Sans** - the numbers does not have the same upper and lower body style (they will look strange on the watch)
* **Lato** - same issue as with _Josefin Sans_ (but not as apparent)
    * This one is a _mabye_. Needs to test on a real watch to make sure

### TODO: ###

- [ ] Check all fonts in the filtered lists at Google Web Fonts and include and document them if they meet the requirements or not
- [ ] Test all fonts that meet the requirements in the simulator
- [ ] All that looks good in the simulator should be tested on a real device
- [ ] Strike-through all fonts that does not look good in the simulator
- [ ] Then choose the most readable font from the real device testing

**Comment by alni** [comment]
Remember to **install** the font then select as font with the BMFont program (do _not_ select the font file directly as additional font as this will result in the spacing of the characters to be wrong!)
